### PR TITLE
Fix redundant package management UX (#218)

### LINKED ISSUE #218: UX: Two redundant ways to add packages with different behavior
## Summary

There are two places in the workspace detail view where users can add packages, with different behavior and no clear guidance on which to use:

1. **Packages tab** → "Install Package" button — accepts comma-separated package names, runs an async job (`pixi add`), and creates a new workspace version
2. **Configuration tab** → Edit pixi.toml — allows editing the full TOML (UI mode or raw), saves synchronously to disk, does NOT run `pixi install`, and does NOT create a version

## Why This Is Confusing

- Two entry points for the same conceptual action (adding a package) with different side effects
- The Packages tab approach actually installs packages and creates a version; the Configuration tab just writes a file
- Users editing pixi.toml in the Configuration tab may not realize their changes aren't installed or versioned
- The Packages tab offers less control (just package names + simple version constraints) while the Configuration tab gives full pixi.toml control

| Aspect | Packages Tab | Configuration Tab |
|--------|-------------|-------------------|
| Runs install | Yes (async job) | No (file write only) |
| Creates version | Yes | No |
| Control level | Package name + basic version | Full pixi.toml |

## Suggestion

The Configuration tab (pixi.toml editing) seems like the more complete and appropriate interface for managing packages. The Packages tab's "Install Package" button is a narrower, less capable duplicate. Consider:

- Removing the install button from the Packages tab and making it read-only (showing currently installed packages)
- Or consolidating into a single package management flow that always goes through pixi.toml editing + an install/apply step

## Relevant Code

- `frontend/src/pages/WorkspaceDetail.tsx` — both tabs defined here
- `frontend/src/components/workspace/PixiTomlEditor.tsx` — configuration tab editor
- `internal/api/handlers/workspace.go` — `InstallPackages` (async job) vs `SavePixiToml` (sync write)

### PR DESCRIPTION
**Pull request by tylerpotts**
Closes #218

## Summary

- **Configuration tab is now the single entry point for package management.** Saving the pixi.toml triggers a `pixi install` job ("Save & Install"), which solves the environment, syncs packages to the database, and creates a new version snapshot.
- **Packages tab is now read-only** — displays installed packages without install/delete buttons. Subtitle directs users to the Configuration tab.
- **Edit workspace screen removed** from the workspace list page, along with the per-row Edit button. Configuration editing lives on the workspace detail's Configuration tab.
- **Recreate workspace feature removed** — no longer needed since Save & Install updates the environment in place.
- **TOML Mode is the default** editor mode (moved to the left of UI Mode).
- **Tab order reordered** to: Overview | Configuration | Versions | Packages | Jobs | ...

### Backend
- `SolveEnvironment` added to `Executor` interface and `LocalExecutor` (runs `pixi install -v`)
- `JobTypeUpdate` handled in the worker (solve, sync packages, create version snapshot)
- `POST /workspaces/:id/solve` endpoint with RBAC write permission and audit logging

### Frontend
- `solveWorkspace()` API client method
- Packages tab: removed install form, delete buttons, and Actions column
- Workspaces list: removed edit card, edit button, and all related state/handlers
- Configuration tab: simplified to Save & Install flow only

## Test plan
- [x] Edit pixi.toml on Configuration tab, click Save & Install — verify job runs, packages sync, version created
- [x] Verify Packages tab is read-only (no install/delete buttons)
- [x] Verify no Edit button on workspace list page
- [x] Verify TOML Mode is the default when clicking Edit on Configuration tab
- [x] Verify tab order: Overview | Configuration | Versions | Packages | Jobs | ...

### CODE REVIEW

File: frontend/src/pages/WorkspaceDetail.tsx [hunk 1]
```diff
@@ -4,26 +4,24 @@ import { buildImportCommand } from '@/lib/registry';
 import { capitalize } from '@/lib/utils';
 import { useWorkspace } from '@/hooks/useWorkspaces';
 import { useModeStore } from '@/store/modeStore';
-import { usePackages, useInstallPackages, useRemovePackage } from '@/hooks/usePackages';
```
Comment (aktech) [inline frontend/src/pages/WorkspaceDetail.tsx:7]: We can now remove the code for unused functions `useInstallPackages` `useRemovePackage`

Comment (tylerpotts) [reply frontend/src/pages/WorkspaceDetail.tsx:7]: Done! Removed both `useInstallPackages` and `useRemovePackage` from `usePackages.ts` along with their tests in `usePackages.test.ts`.
